// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto_new/friends.proto

package proto_new

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 好友服务消息
type AddFriendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendUsername string                 `protobuf:"bytes,2,opt,name=friend_username,json=friendUsername,proto3" json:"friend_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddFriendRequest) Reset() {
	*x = AddFriendRequest{}
	mi := &file_proto_new_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequest) ProtoMessage() {}

func (x *AddFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequest.ProtoReflect.Descriptor instead.
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{0}
}

func (x *AddFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddFriendRequest) GetFriendUsername() string {
	if x != nil {
		return x.FriendUsername
	}
	return ""
}

type AddFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendResponse) Reset() {
	*x = AddFriendResponse{}
	mi := &file_proto_new_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendResponse) ProtoMessage() {}

func (x *AddFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendResponse.ProtoReflect.Descriptor instead.
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{1}
}

func (x *AddFriendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddFriendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendUserId  string                 `protobuf:"bytes,2,opt,name=friend_user_id,json=friendUserId,proto3" json:"friend_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_proto_new_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFriendRequest) GetFriendUserId() string {
	if x != nil {
		return x.FriendUserId
	}
	return ""
}

type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_proto_new_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFriendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFriendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequest) Reset() {
	*x = GetFriendsRequest{}
	mi := &file_proto_new_friends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequest) ProtoMessage() {}

func (x *GetFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Friends       []*FriendInfo          `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResponse) Reset() {
	*x = GetFriendsResponse{}
	mi := &file_proto_new_friends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResponse) ProtoMessage() {}

func (x *GetFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{5}
}

func (x *GetFriendsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFriendsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFriendsResponse) GetFriends() []*FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_proto_new_friends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{6}
}

func (x *SendFriendRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendFriendRequestRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_proto_new_friends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{7}
}

func (x *SendFriendRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RespondFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestUserId string                 `protobuf:"bytes,2,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"` // true to accept, false to reject
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondFriendRequestRequest) Reset() {
	*x = RespondFriendRequestRequest{}
	mi := &file_proto_new_friends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondFriendRequestRequest) ProtoMessage() {}

func (x *RespondFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*RespondFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{8}
}

func (x *RespondFriendRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RespondFriendRequestRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *RespondFriendRequestRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RespondFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondFriendRequestResponse) Reset() {
	*x = RespondFriendRequestResponse{}
	mi := &file_proto_new_friends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondFriendRequestResponse) ProtoMessage() {}

func (x *RespondFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_friends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*RespondFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_friends_proto_rawDescGZIP(), []int{9}
}

func (x *RespondFriendRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RespondFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_new_friends_proto protoreflect.FileDescriptor

const file_proto_new_friends_proto_rawDesc = "" +
	"\n" +
	"\x17proto_new/friends.proto\x12\x0ffriends_service\x1a\x16proto_new/common.proto\"T\n" +
	"\x10AddFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ffriend_username\x18\x02 \x01(\tR\x0efriendUsername\"G\n" +
	"\x11AddFriendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x13RemoveFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0efriend_user_id\x18\x02 \x01(\tR\ffriendUserId\"J\n" +
	"\x14RemoveFriendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11GetFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"v\n" +
	"\x12GetFriendsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\afriends\x18\x03 \x03(\v2\x12.common.FriendInfoR\afriends\"Y\n" +
	"\x18SendFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"O\n" +
	"\x19SendFriendRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"z\n" +
	"\x1bRespondFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0frequest_user_id\x18\x02 \x01(\tR\rrequestUserId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\"R\n" +
	"\x1cRespondFriendRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf9\x03\n" +
	"\x0eFriendsService\x12R\n" +
	"\tAddFriend\x12!.friends_service.AddFriendRequest\x1a\".friends_service.AddFriendResponse\x12[\n" +
	"\fRemoveFriend\x12$.friends_service.RemoveFriendRequest\x1a%.friends_service.RemoveFriendResponse\x12U\n" +
	"\n" +
	"GetFriends\x12\".friends_service.GetFriendsRequest\x1a#.friends_service.GetFriendsResponse\x12j\n" +
	"\x11SendFriendRequest\x12).friends_service.SendFriendRequestRequest\x1a*.friends_service.SendFriendRequestResponse\x12s\n" +
	"\x14RespondFriendRequest\x12,.friends_service.RespondFriendRequestRequest\x1a-.friends_service.RespondFriendRequestResponseB\rZ\v./proto_newb\x06proto3"

var (
	file_proto_new_friends_proto_rawDescOnce sync.Once
	file_proto_new_friends_proto_rawDescData []byte
)

func file_proto_new_friends_proto_rawDescGZIP() []byte {
	file_proto_new_friends_proto_rawDescOnce.Do(func() {
		file_proto_new_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_new_friends_proto_rawDesc), len(file_proto_new_friends_proto_rawDesc)))
	})
	return file_proto_new_friends_proto_rawDescData
}

var file_proto_new_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_new_friends_proto_goTypes = []any{
	(*AddFriendRequest)(nil),             // 0: friends_service.AddFriendRequest
	(*AddFriendResponse)(nil),            // 1: friends_service.AddFriendResponse
	(*RemoveFriendRequest)(nil),          // 2: friends_service.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 3: friends_service.RemoveFriendResponse
	(*GetFriendsRequest)(nil),            // 4: friends_service.GetFriendsRequest
	(*GetFriendsResponse)(nil),           // 5: friends_service.GetFriendsResponse
	(*SendFriendRequestRequest)(nil),     // 6: friends_service.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 7: friends_service.SendFriendRequestResponse
	(*RespondFriendRequestRequest)(nil),  // 8: friends_service.RespondFriendRequestRequest
	(*RespondFriendRequestResponse)(nil), // 9: friends_service.RespondFriendRequestResponse
	(*FriendInfo)(nil),                   // 10: common.FriendInfo
}
var file_proto_new_friends_proto_depIdxs = []int32{
	10, // 0: friends_service.GetFriendsResponse.friends:type_name -> common.FriendInfo
	0,  // 1: friends_service.FriendsService.AddFriend:input_type -> friends_service.AddFriendRequest
	2,  // 2: friends_service.FriendsService.RemoveFriend:input_type -> friends_service.RemoveFriendRequest
	4,  // 3: friends_service.FriendsService.GetFriends:input_type -> friends_service.GetFriendsRequest
	6,  // 4: friends_service.FriendsService.SendFriendRequest:input_type -> friends_service.SendFriendRequestRequest
	8,  // 5: friends_service.FriendsService.RespondFriendRequest:input_type -> friends_service.RespondFriendRequestRequest
	1,  // 6: friends_service.FriendsService.AddFriend:output_type -> friends_service.AddFriendResponse
	3,  // 7: friends_service.FriendsService.RemoveFriend:output_type -> friends_service.RemoveFriendResponse
	5,  // 8: friends_service.FriendsService.GetFriends:output_type -> friends_service.GetFriendsResponse
	7,  // 9: friends_service.FriendsService.SendFriendRequest:output_type -> friends_service.SendFriendRequestResponse
	9,  // 10: friends_service.FriendsService.RespondFriendRequest:output_type -> friends_service.RespondFriendRequestResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_new_friends_proto_init() }
func file_proto_new_friends_proto_init() {
	if File_proto_new_friends_proto != nil {
		return
	}
	file_proto_new_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_new_friends_proto_rawDesc), len(file_proto_new_friends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_new_friends_proto_goTypes,
		DependencyIndexes: file_proto_new_friends_proto_depIdxs,
		MessageInfos:      file_proto_new_friends_proto_msgTypes,
	}.Build()
	File_proto_new_friends_proto = out.File
	file_proto_new_friends_proto_goTypes = nil
	file_proto_new_friends_proto_depIdxs = nil
}
