// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto_new/leaderboard.proto

package proto_new

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 排行榜服务消息
type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_proto_new_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_proto_new_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeaderboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLeaderboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UpdateScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	GameWon       bool                   `protobuf:"varint,3,opt,name=game_won,json=gameWon,proto3" json:"game_won,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreRequest) Reset() {
	*x = UpdateScoreRequest{}
	mi := &file_proto_new_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreRequest) ProtoMessage() {}

func (x *UpdateScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateScoreRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpdateScoreRequest) GetGameWon() bool {
	if x != nil {
		return x.GameWon
	}
	return false
}

type UpdateScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewScore      int32                  `protobuf:"varint,3,opt,name=new_score,json=newScore,proto3" json:"new_score,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreResponse) Reset() {
	*x = UpdateScoreResponse{}
	mi := &file_proto_new_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreResponse) ProtoMessage() {}

func (x *UpdateScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateScoreResponse) GetNewScore() int32 {
	if x != nil {
		return x.NewScore
	}
	return 0
}

func (x *UpdateScoreResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetUserRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRankRequest) Reset() {
	*x = GetUserRankRequest{}
	mi := &file_proto_new_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRankRequest) ProtoMessage() {}

func (x *GetUserRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRankRequest.ProtoReflect.Descriptor instead.
func (*GetUserRankRequest) Descriptor() ([]byte, []int) {
	return file_proto_new_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRankRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,4,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRankResponse) Reset() {
	*x = GetUserRankResponse{}
	mi := &file_proto_new_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRankResponse) ProtoMessage() {}

func (x *GetUserRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_new_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRankResponse.ProtoReflect.Descriptor instead.
func (*GetUserRankResponse) Descriptor() ([]byte, []int) {
	return file_proto_new_leaderboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserRankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetUserRankResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

var File_proto_new_leaderboard_proto protoreflect.FileDescriptor

const file_proto_new_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x1bproto_new/leaderboard.proto\x12\x13leaderboard_service\x1a\x16proto_new/common.proto\"E\n" +
	"\x15GetLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x80\x01\n" +
	"\x16GetLeaderboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\aentries\x18\x03 \x03(\v2\x18.common.LeaderboardEntryR\aentries\"^\n" +
	"\x12UpdateScoreRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x19\n" +
	"\bgame_won\x18\x03 \x01(\bR\agameWon\"z\n" +
	"\x13UpdateScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tnew_score\x18\x03 \x01(\x05R\bnewScore\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"-\n" +
	"\x12GetUserRankRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x13GetUserRankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x1f\n" +
	"\vtotal_users\x18\x04 \x01(\x05R\n" +
	"totalUsers2\xc3\x02\n" +
	"\x12LeaderboardService\x12i\n" +
	"\x0eGetLeaderboard\x12*.leaderboard_service.GetLeaderboardRequest\x1a+.leaderboard_service.GetLeaderboardResponse\x12`\n" +
	"\vUpdateScore\x12'.leaderboard_service.UpdateScoreRequest\x1a(.leaderboard_service.UpdateScoreResponse\x12`\n" +
	"\vGetUserRank\x12'.leaderboard_service.GetUserRankRequest\x1a(.leaderboard_service.GetUserRankResponseB\rZ\v./proto_newb\x06proto3"

var (
	file_proto_new_leaderboard_proto_rawDescOnce sync.Once
	file_proto_new_leaderboard_proto_rawDescData []byte
)

func file_proto_new_leaderboard_proto_rawDescGZIP() []byte {
	file_proto_new_leaderboard_proto_rawDescOnce.Do(func() {
		file_proto_new_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_new_leaderboard_proto_rawDesc), len(file_proto_new_leaderboard_proto_rawDesc)))
	})
	return file_proto_new_leaderboard_proto_rawDescData
}

var file_proto_new_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_new_leaderboard_proto_goTypes = []any{
	(*GetLeaderboardRequest)(nil),  // 0: leaderboard_service.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil), // 1: leaderboard_service.GetLeaderboardResponse
	(*UpdateScoreRequest)(nil),     // 2: leaderboard_service.UpdateScoreRequest
	(*UpdateScoreResponse)(nil),    // 3: leaderboard_service.UpdateScoreResponse
	(*GetUserRankRequest)(nil),     // 4: leaderboard_service.GetUserRankRequest
	(*GetUserRankResponse)(nil),    // 5: leaderboard_service.GetUserRankResponse
	(*LeaderboardEntry)(nil),       // 6: common.LeaderboardEntry
}
var file_proto_new_leaderboard_proto_depIdxs = []int32{
	6, // 0: leaderboard_service.GetLeaderboardResponse.entries:type_name -> common.LeaderboardEntry
	0, // 1: leaderboard_service.LeaderboardService.GetLeaderboard:input_type -> leaderboard_service.GetLeaderboardRequest
	2, // 2: leaderboard_service.LeaderboardService.UpdateScore:input_type -> leaderboard_service.UpdateScoreRequest
	4, // 3: leaderboard_service.LeaderboardService.GetUserRank:input_type -> leaderboard_service.GetUserRankRequest
	1, // 4: leaderboard_service.LeaderboardService.GetLeaderboard:output_type -> leaderboard_service.GetLeaderboardResponse
	3, // 5: leaderboard_service.LeaderboardService.UpdateScore:output_type -> leaderboard_service.UpdateScoreResponse
	5, // 6: leaderboard_service.LeaderboardService.GetUserRank:output_type -> leaderboard_service.GetUserRankResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_new_leaderboard_proto_init() }
func file_proto_new_leaderboard_proto_init() {
	if File_proto_new_leaderboard_proto != nil {
		return
	}
	file_proto_new_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_new_leaderboard_proto_rawDesc), len(file_proto_new_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_new_leaderboard_proto_goTypes,
		DependencyIndexes: file_proto_new_leaderboard_proto_depIdxs,
		MessageInfos:      file_proto_new_leaderboard_proto_msgTypes,
	}.Build()
	File_proto_new_leaderboard_proto = out.File
	file_proto_new_leaderboard_proto_goTypes = nil
	file_proto_new_leaderboard_proto_depIdxs = nil
}
