// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto_new/matching.proto

package proto_new

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingService_FindMatch_FullMethodName         = "/matching_service.MatchingService/FindMatch"
	MatchingService_CancelMatch_FullMethodName       = "/matching_service.MatchingService/CancelMatch"
	MatchingService_GetWaitingPlayers_FullMethodName = "/matching_service.MatchingService/GetWaitingPlayers"
	MatchingService_GetOnlinePlayers_FullMethodName  = "/matching_service.MatchingService/GetOnlinePlayers"
)

// MatchingServiceClient is the client API for MatchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 匹配服务
type MatchingServiceClient interface {
	// 寻找匹配
	FindMatch(ctx context.Context, in *FindMatchRequest, opts ...grpc.CallOption) (*FindMatchResponse, error)
	// 取消匹配
	CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*CancelMatchResponse, error)
	// 获取等待玩家数量
	GetWaitingPlayers(ctx context.Context, in *GetWaitingPlayersRequest, opts ...grpc.CallOption) (*GetWaitingPlayersResponse, error)
	// 获取在线玩家
	GetOnlinePlayers(ctx context.Context, in *GetOnlinePlayersRequest, opts ...grpc.CallOption) (*GetOnlinePlayersResponse, error)
}

type matchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingServiceClient(cc grpc.ClientConnInterface) MatchingServiceClient {
	return &matchingServiceClient{cc}
}

func (c *matchingServiceClient) FindMatch(ctx context.Context, in *FindMatchRequest, opts ...grpc.CallOption) (*FindMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindMatchResponse)
	err := c.cc.Invoke(ctx, MatchingService_FindMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*CancelMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMatchResponse)
	err := c.cc.Invoke(ctx, MatchingService_CancelMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetWaitingPlayers(ctx context.Context, in *GetWaitingPlayersRequest, opts ...grpc.CallOption) (*GetWaitingPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWaitingPlayersResponse)
	err := c.cc.Invoke(ctx, MatchingService_GetWaitingPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetOnlinePlayers(ctx context.Context, in *GetOnlinePlayersRequest, opts ...grpc.CallOption) (*GetOnlinePlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlinePlayersResponse)
	err := c.cc.Invoke(ctx, MatchingService_GetOnlinePlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingServiceServer is the server API for MatchingService service.
// All implementations must embed UnimplementedMatchingServiceServer
// for forward compatibility.
//
// 匹配服务
type MatchingServiceServer interface {
	// 寻找匹配
	FindMatch(context.Context, *FindMatchRequest) (*FindMatchResponse, error)
	// 取消匹配
	CancelMatch(context.Context, *CancelMatchRequest) (*CancelMatchResponse, error)
	// 获取等待玩家数量
	GetWaitingPlayers(context.Context, *GetWaitingPlayersRequest) (*GetWaitingPlayersResponse, error)
	// 获取在线玩家
	GetOnlinePlayers(context.Context, *GetOnlinePlayersRequest) (*GetOnlinePlayersResponse, error)
	mustEmbedUnimplementedMatchingServiceServer()
}

// UnimplementedMatchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServiceServer struct{}

func (UnimplementedMatchingServiceServer) FindMatch(context.Context, *FindMatchRequest) (*FindMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMatch not implemented")
}
func (UnimplementedMatchingServiceServer) CancelMatch(context.Context, *CancelMatchRequest) (*CancelMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMatch not implemented")
}
func (UnimplementedMatchingServiceServer) GetWaitingPlayers(context.Context, *GetWaitingPlayersRequest) (*GetWaitingPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWaitingPlayers not implemented")
}
func (UnimplementedMatchingServiceServer) GetOnlinePlayers(context.Context, *GetOnlinePlayersRequest) (*GetOnlinePlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnlinePlayers not implemented")
}
func (UnimplementedMatchingServiceServer) mustEmbedUnimplementedMatchingServiceServer() {}
func (UnimplementedMatchingServiceServer) testEmbeddedByValue()                         {}

// UnsafeMatchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServiceServer will
// result in compilation errors.
type UnsafeMatchingServiceServer interface {
	mustEmbedUnimplementedMatchingServiceServer()
}

func RegisterMatchingServiceServer(s grpc.ServiceRegistrar, srv MatchingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingService_ServiceDesc, srv)
}

func _MatchingService_FindMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).FindMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_FindMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).FindMatch(ctx, req.(*FindMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_CancelMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_CancelMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).CancelMatch(ctx, req.(*CancelMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetWaitingPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaitingPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetWaitingPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetWaitingPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetWaitingPlayers(ctx, req.(*GetWaitingPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetOnlinePlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlinePlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetOnlinePlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetOnlinePlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetOnlinePlayers(ctx, req.(*GetOnlinePlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingService_ServiceDesc is the grpc.ServiceDesc for MatchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching_service.MatchingService",
	HandlerType: (*MatchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMatch",
			Handler:    _MatchingService_FindMatch_Handler,
		},
		{
			MethodName: "CancelMatch",
			Handler:    _MatchingService_CancelMatch_Handler,
		},
		{
			MethodName: "GetWaitingPlayers",
			Handler:    _MatchingService_GetWaitingPlayers_Handler,
		},
		{
			MethodName: "GetOnlinePlayers",
			Handler:    _MatchingService_GetOnlinePlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto_new/matching.proto",
}
