// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 游戏服务消息
type GameUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // snake_moved, food_eaten, game_over, etc.
	Snakes            []*GameSnake           `protobuf:"bytes,2,rep,name=snakes,proto3" json:"snakes,omitempty"`
	Foods             []*Position            `protobuf:"bytes,3,rep,name=foods,proto3" json:"foods,omitempty"`
	Walls             []*Position            `protobuf:"bytes,4,rep,name=walls,proto3" json:"walls,omitempty"`
	EliminatedPlayers []string               `protobuf:"bytes,5,rep,name=eliminated_players,json=eliminatedPlayers,proto3" json:"eliminated_players,omitempty"`
	WinnerPlayerId    string                 `protobuf:"bytes,6,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameUpdate) Reset() {
	*x = GameUpdate{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdate) ProtoMessage() {}

func (x *GameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdate.ProtoReflect.Descriptor instead.
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GameUpdate) GetSnakes() []*GameSnake {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *GameUpdate) GetFoods() []*Position {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *GameUpdate) GetWalls() []*Position {
	if x != nil {
		return x.Walls
	}
	return nil
}

func (x *GameUpdate) GetEliminatedPlayers() []string {
	if x != nil {
		return x.EliminatedPlayers
	}
	return nil
}

func (x *GameUpdate) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

func (x *GameUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	InitialSnakes []*GameSnake           `protobuf:"bytes,3,rep,name=initial_snakes,json=initialSnakes,proto3" json:"initial_snakes,omitempty"`
	Foods         []*Position            `protobuf:"bytes,4,rep,name=foods,proto3" json:"foods,omitempty"`
	Walls         []*Position            `protobuf:"bytes,5,rep,name=walls,proto3" json:"walls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinGameResponse) GetInitialSnakes() []*GameSnake {
	if x != nil {
		return x.InitialSnakes
	}
	return nil
}

func (x *JoinGameResponse) GetFoods() []*Position {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *JoinGameResponse) GetWalls() []*Position {
	if x != nil {
		return x.Walls
	}
	return nil
}

type LeaveGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGameRequest) Reset() {
	*x = LeaveGameRequest{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameRequest) ProtoMessage() {}

func (x *LeaveGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameRequest.ProtoReflect.Descriptor instead.
func (*LeaveGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LeaveGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGameResponse) Reset() {
	*x = LeaveGameResponse{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameResponse) ProtoMessage() {}

func (x *LeaveGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameResponse.ProtoReflect.Descriptor instead.
func (*LeaveGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=common.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *MoveRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_NONE
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Snakes        []*GameSnake           `protobuf:"bytes,3,rep,name=snakes,proto3" json:"snakes,omitempty"`
	Foods         []*Position            `protobuf:"bytes,4,rep,name=foods,proto3" json:"foods,omitempty"`
	Walls         []*Position            `protobuf:"bytes,5,rep,name=walls,proto3" json:"walls,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *GetGameStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGameStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameStateResponse) GetSnakes() []*GameSnake {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *GetGameStateResponse) GetFoods() []*Position {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *GetGameStateResponse) GetWalls() []*Position {
	if x != nil {
		return x.Walls
	}
	return nil
}

func (x *GetGameStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubscribeGameUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeGameUpdatesRequest) Reset() {
	*x = SubscribeGameUpdatesRequest{}
	mi := &file_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeGameUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeGameUpdatesRequest) ProtoMessage() {}

func (x *SubscribeGameUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeGameUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeGameUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeGameUpdatesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubscribeGameUpdatesRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\fgame_service\x1a\x12proto/common.proto\"\x8c\x02\n" +
	"\n" +
	"GameUpdate\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12)\n" +
	"\x06snakes\x18\x02 \x03(\v2\x11.common.GameSnakeR\x06snakes\x12&\n" +
	"\x05foods\x18\x03 \x03(\v2\x10.common.PositionR\x05foods\x12&\n" +
	"\x05walls\x18\x04 \x03(\v2\x10.common.PositionR\x05walls\x12-\n" +
	"\x12eliminated_players\x18\x05 \x03(\tR\x11eliminatedPlayers\x12(\n" +
	"\x10winner_player_id\x18\x06 \x01(\tR\x0ewinnerPlayerId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"G\n" +
	"\x0fJoinGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\xd0\x01\n" +
	"\x10JoinGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\x0einitial_snakes\x18\x03 \x03(\v2\x11.common.GameSnakeR\rinitialSnakes\x12&\n" +
	"\x05foods\x18\x04 \x03(\v2\x10.common.PositionR\x05foods\x12&\n" +
	"\x05walls\x18\x05 \x03(\v2\x10.common.PositionR\x05walls\"H\n" +
	"\x10LeaveGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"G\n" +
	"\x11LeaveGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\vMoveRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12/\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x11.common.DirectionR\tdirection\"B\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x13GetGameStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xdd\x01\n" +
	"\x14GetGameStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06snakes\x18\x03 \x03(\v2\x11.common.GameSnakeR\x06snakes\x12&\n" +
	"\x05foods\x18\x04 \x03(\v2\x10.common.PositionR\x05foods\x12&\n" +
	"\x05walls\x18\x05 \x03(\v2\x10.common.PositionR\x05walls\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"S\n" +
	"\x1bSubscribeGameUpdatesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId2\x9b\x03\n" +
	"\vGameService\x12I\n" +
	"\bJoinGame\x12\x1d.game_service.JoinGameRequest\x1a\x1e.game_service.JoinGameResponse\x12L\n" +
	"\tLeaveGame\x12\x1e.game_service.LeaveGameRequest\x1a\x1f.game_service.LeaveGameResponse\x12=\n" +
	"\x04Move\x12\x19.game_service.MoveRequest\x1a\x1a.game_service.MoveResponse\x12U\n" +
	"\fGetGameState\x12!.game_service.GetGameStateRequest\x1a\".game_service.GetGameStateResponse\x12]\n" +
	"\x14SubscribeGameUpdates\x12).game_service.SubscribeGameUpdatesRequest\x1a\x18.game_service.GameUpdate0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_game_proto_goTypes = []any{
	(*GameUpdate)(nil),                  // 0: game_service.GameUpdate
	(*JoinGameRequest)(nil),             // 1: game_service.JoinGameRequest
	(*JoinGameResponse)(nil),            // 2: game_service.JoinGameResponse
	(*LeaveGameRequest)(nil),            // 3: game_service.LeaveGameRequest
	(*LeaveGameResponse)(nil),           // 4: game_service.LeaveGameResponse
	(*MoveRequest)(nil),                 // 5: game_service.MoveRequest
	(*MoveResponse)(nil),                // 6: game_service.MoveResponse
	(*GetGameStateRequest)(nil),         // 7: game_service.GetGameStateRequest
	(*GetGameStateResponse)(nil),        // 8: game_service.GetGameStateResponse
	(*SubscribeGameUpdatesRequest)(nil), // 9: game_service.SubscribeGameUpdatesRequest
	(*GameSnake)(nil),                   // 10: common.GameSnake
	(*Position)(nil),                    // 11: common.Position
	(Direction)(0),                      // 12: common.Direction
}
var file_proto_game_proto_depIdxs = []int32{
	10, // 0: game_service.GameUpdate.snakes:type_name -> common.GameSnake
	11, // 1: game_service.GameUpdate.foods:type_name -> common.Position
	11, // 2: game_service.GameUpdate.walls:type_name -> common.Position
	10, // 3: game_service.JoinGameResponse.initial_snakes:type_name -> common.GameSnake
	11, // 4: game_service.JoinGameResponse.foods:type_name -> common.Position
	11, // 5: game_service.JoinGameResponse.walls:type_name -> common.Position
	12, // 6: game_service.MoveRequest.direction:type_name -> common.Direction
	10, // 7: game_service.GetGameStateResponse.snakes:type_name -> common.GameSnake
	11, // 8: game_service.GetGameStateResponse.foods:type_name -> common.Position
	11, // 9: game_service.GetGameStateResponse.walls:type_name -> common.Position
	1,  // 10: game_service.GameService.JoinGame:input_type -> game_service.JoinGameRequest
	3,  // 11: game_service.GameService.LeaveGame:input_type -> game_service.LeaveGameRequest
	5,  // 12: game_service.GameService.Move:input_type -> game_service.MoveRequest
	7,  // 13: game_service.GameService.GetGameState:input_type -> game_service.GetGameStateRequest
	9,  // 14: game_service.GameService.SubscribeGameUpdates:input_type -> game_service.SubscribeGameUpdatesRequest
	2,  // 15: game_service.GameService.JoinGame:output_type -> game_service.JoinGameResponse
	4,  // 16: game_service.GameService.LeaveGame:output_type -> game_service.LeaveGameResponse
	6,  // 17: game_service.GameService.Move:output_type -> game_service.MoveResponse
	8,  // 18: game_service.GameService.GetGameState:output_type -> game_service.GetGameStateResponse
	0,  // 19: game_service.GameService.SubscribeGameUpdates:output_type -> game_service.GameUpdate
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
