// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/matching.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 匹配服务消息
type FindMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMatchRequest) Reset() {
	*x = FindMatchRequest{}
	mi := &file_proto_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchRequest) ProtoMessage() {}

func (x *FindMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchRequest.ProtoReflect.Descriptor instead.
func (*FindMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{0}
}

func (x *FindMatchRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FindMatchRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FindMatchRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type FindMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players       []*PlayerInfo          `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMatchResponse) Reset() {
	*x = FindMatchResponse{}
	mi := &file_proto_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchResponse) ProtoMessage() {}

func (x *FindMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchResponse.ProtoReflect.Descriptor instead.
func (*FindMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{1}
}

func (x *FindMatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindMatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindMatchResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *FindMatchResponse) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type CancelMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequest) Reset() {
	*x = CancelMatchRequest{}
	mi := &file_proto_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequest) ProtoMessage() {}

func (x *CancelMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{2}
}

func (x *CancelMatchRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CancelMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchResponse) Reset() {
	*x = CancelMatchResponse{}
	mi := &file_proto_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchResponse) ProtoMessage() {}

func (x *CancelMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchResponse.ProtoReflect.Descriptor instead.
func (*CancelMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{3}
}

func (x *CancelMatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelMatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWaitingPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaitingPlayersRequest) Reset() {
	*x = GetWaitingPlayersRequest{}
	mi := &file_proto_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaitingPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitingPlayersRequest) ProtoMessage() {}

func (x *GetWaitingPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitingPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetWaitingPlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{4}
}

type GetWaitingPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaitingPlayersResponse) Reset() {
	*x = GetWaitingPlayersResponse{}
	mi := &file_proto_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaitingPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitingPlayersResponse) ProtoMessage() {}

func (x *GetWaitingPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitingPlayersResponse.ProtoReflect.Descriptor instead.
func (*GetWaitingPlayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{5}
}

func (x *GetWaitingPlayersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetOnlinePlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlinePlayersRequest) Reset() {
	*x = GetOnlinePlayersRequest{}
	mi := &file_proto_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlinePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlinePlayersRequest) ProtoMessage() {}

func (x *GetOnlinePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlinePlayersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlinePlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{6}
}

type GetOnlinePlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Players       []*PlayerInfo          `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlinePlayersResponse) Reset() {
	*x = GetOnlinePlayersResponse{}
	mi := &file_proto_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlinePlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlinePlayersResponse) ProtoMessage() {}

func (x *GetOnlinePlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlinePlayersResponse.ProtoReflect.Descriptor instead.
func (*GetOnlinePlayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{7}
}

func (x *GetOnlinePlayersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOnlinePlayersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOnlinePlayersResponse) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_proto_matching_proto protoreflect.FileDescriptor

const file_proto_matching_proto_rawDesc = "" +
	"\n" +
	"\x14proto/matching.proto\x12\x10matching_service\x1a\x12proto/common.proto\"c\n" +
	"\x10FindMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"\x8e\x01\n" +
	"\x11FindMatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12,\n" +
	"\aplayers\x18\x04 \x03(\v2\x12.common.PlayerInfoR\aplayers\"1\n" +
	"\x12CancelMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"I\n" +
	"\x13CancelMatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18GetWaitingPlayersRequest\"1\n" +
	"\x19GetWaitingPlayersResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x19\n" +
	"\x17GetOnlinePlayersRequest\"|\n" +
	"\x18GetOnlinePlayersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\aplayers\x18\x03 \x03(\v2\x12.common.PlayerInfoR\aplayers2\x9c\x03\n" +
	"\x0fMatchingService\x12T\n" +
	"\tFindMatch\x12\".matching_service.FindMatchRequest\x1a#.matching_service.FindMatchResponse\x12Z\n" +
	"\vCancelMatch\x12$.matching_service.CancelMatchRequest\x1a%.matching_service.CancelMatchResponse\x12l\n" +
	"\x11GetWaitingPlayers\x12*.matching_service.GetWaitingPlayersRequest\x1a+.matching_service.GetWaitingPlayersResponse\x12i\n" +
	"\x10GetOnlinePlayers\x12).matching_service.GetOnlinePlayersRequest\x1a*.matching_service.GetOnlinePlayersResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_matching_proto_rawDescOnce sync.Once
	file_proto_matching_proto_rawDescData []byte
)

func file_proto_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)))
	})
	return file_proto_matching_proto_rawDescData
}

var file_proto_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_matching_proto_goTypes = []any{
	(*FindMatchRequest)(nil),          // 0: matching_service.FindMatchRequest
	(*FindMatchResponse)(nil),         // 1: matching_service.FindMatchResponse
	(*CancelMatchRequest)(nil),        // 2: matching_service.CancelMatchRequest
	(*CancelMatchResponse)(nil),       // 3: matching_service.CancelMatchResponse
	(*GetWaitingPlayersRequest)(nil),  // 4: matching_service.GetWaitingPlayersRequest
	(*GetWaitingPlayersResponse)(nil), // 5: matching_service.GetWaitingPlayersResponse
	(*GetOnlinePlayersRequest)(nil),   // 6: matching_service.GetOnlinePlayersRequest
	(*GetOnlinePlayersResponse)(nil),  // 7: matching_service.GetOnlinePlayersResponse
	(*PlayerInfo)(nil),                // 8: common.PlayerInfo
}
var file_proto_matching_proto_depIdxs = []int32{
	8, // 0: matching_service.FindMatchResponse.players:type_name -> common.PlayerInfo
	8, // 1: matching_service.GetOnlinePlayersResponse.players:type_name -> common.PlayerInfo
	0, // 2: matching_service.MatchingService.FindMatch:input_type -> matching_service.FindMatchRequest
	2, // 3: matching_service.MatchingService.CancelMatch:input_type -> matching_service.CancelMatchRequest
	4, // 4: matching_service.MatchingService.GetWaitingPlayers:input_type -> matching_service.GetWaitingPlayersRequest
	6, // 5: matching_service.MatchingService.GetOnlinePlayers:input_type -> matching_service.GetOnlinePlayersRequest
	1, // 6: matching_service.MatchingService.FindMatch:output_type -> matching_service.FindMatchResponse
	3, // 7: matching_service.MatchingService.CancelMatch:output_type -> matching_service.CancelMatchResponse
	5, // 8: matching_service.MatchingService.GetWaitingPlayers:output_type -> matching_service.GetWaitingPlayersResponse
	7, // 9: matching_service.MatchingService.GetOnlinePlayers:output_type -> matching_service.GetOnlinePlayersResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_matching_proto_init() }
func file_proto_matching_proto_init() {
	if File_proto_matching_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_proto_depIdxs,
		MessageInfos:      file_proto_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_proto = out.File
	file_proto_matching_proto_goTypes = nil
	file_proto_matching_proto_depIdxs = nil
}
